export enum MixPanelEvents {
  CLOSE_VERIFICATION_BAD_COMMAND = "CLOSE_VERIFICATION_BAD_COMMAND",
  CLOSE_VERIFICATION_MISSING_SPACE = "CLOSE_VERIFICATION_MISSING_SPACE",
  VERIFICATION_SUCCESS = "VERIFICATION_SUCCESS",
  VERIFICATION_FAIL_EXPIRED = "VERIFICATION_FAIL_EXPIRED",
  VERIFICATION_FAIL_BAD_CODE = "VERIFICATION_FAIL_BAD_CODE",
  SUSPEND = "SUSPEND",
  UNSUSPEND = "UNSUSPEND",
  CYCLE_VERIFY = "CYCLE_VERIFY",
  USER_JOIN_WELCOME_MESSAGE = "USER_JOIN_WELCOME_MESSAGE"

}
